# Generated by Django 4.2.7 on 2025-03-01 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAssistantPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titel')),
                ('prompt', models.TextField(verbose_name='Prompt')),
                ('category', models.CharField(choices=[('general', 'Allgemein'), ('therapy', 'Therapie'), ('mental_health', 'Psychische Gesundheit'), ('motivation', 'Motivation'), ('meditation', 'Meditation')], max_length=20, verbose_name='Kategorie')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'KI-Assistent-Prompt',
                'verbose_name_plural': 'KI-Assistent-Prompts',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Inhalt')),
                ('sender', models.CharField(choices=[('user', 'Benutzer'), ('assistant', 'Assistent')], max_length=10, verbose_name='Absender')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Zeitstempel')),
                ('is_read', models.BooleanField(default=False, verbose_name='Gelesen')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Metadaten')),
            ],
            options={
                'verbose_name': 'Chat-Nachricht',
                'verbose_name_plural': 'Chat-Nachrichten',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titel')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Chat-Sitzung',
                'verbose_name_plural': 'Chat-Sitzungen',
                'ordering': ['-updated_at'],
            },
        ),
    ]
