# Generated by Django 4.2.7 on 2025-03-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titel')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('icon', models.CharField(help_text='Emoji oder Icon-Name', max_length=50, verbose_name='Icon')),
                ('category', models.CharField(choices=[('meditation', 'Meditation'), ('journaling', 'Journaling'), ('streak', 'Serie'), ('milestones', 'Meilensteine'), ('social', 'Sozial')], max_length=20, verbose_name='Kategorie')),
                ('required_value', models.PositiveIntegerField(help_text='Z.B. Anzahl der Übungen oder Tage', verbose_name='Benötigter Wert')),
                ('points', models.PositiveIntegerField(default=50, verbose_name='Belohnungspunkte')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['category', 'required_value'],
            },
        ),
        migrations.CreateModel(
            name='CompletedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Abgeschlossen am')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
            ],
            options={
                'verbose_name': 'Abgeschlossene Übung',
                'verbose_name_plural': 'Abgeschlossene Übungen',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Inhalt')),
                ('type', models.CharField(choices=[('reflection', 'Reflexion'), ('gratitude', 'Dankbarkeit'), ('challenge', 'Herausforderung'), ('mindfulness', 'Achtsamkeit')], max_length=20, verbose_name='Typ')),
                ('date', models.DateField(unique=True, verbose_name='Datum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
            ],
            options={
                'verbose_name': 'Täglicher Prompt',
                'verbose_name_plural': 'Tägliche Prompts',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titel')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('type', models.CharField(choices=[('meditation', 'Meditation'), ('journaling', 'Journaling'), ('breathwork', 'Atemübung'), ('cognitive', 'Kognitive Übung'), ('behavioral', 'Verhaltensübung')], max_length=20, verbose_name='Typ')),
                ('duration_minutes', models.PositiveIntegerField(default=10, verbose_name='Dauer (Minuten)')),
                ('points', models.PositiveIntegerField(default=10, verbose_name='Punkte')),
                ('content', models.TextField(help_text='Detaillierter Inhalt oder Anleitung der Übung', verbose_name='Inhalt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Übung',
                'verbose_name_plural': 'Übungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_exercises_completed', models.PositiveIntegerField(default=0, verbose_name='Insgesamt abgeschlossene Übungen')),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='Aktuelle Serie')),
                ('longest_streak', models.PositiveIntegerField(default=0, verbose_name='Längste Serie')),
                ('last_activity_date', models.DateField(blank=True, null=True, verbose_name='Letztes Aktivitätsdatum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Fortschrittsstatistik',
                'verbose_name_plural': 'Fortschrittsstatistiken',
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='Freigeschaltet am')),
                ('current_value', models.PositiveIntegerField(default=0, verbose_name='Aktueller Wert')),
            ],
            options={
                'verbose_name': 'Benutzer-Achievement',
                'verbose_name_plural': 'Benutzer-Achievements',
                'ordering': ['-unlocked_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Anzahl der Aktivitäten')),
            ],
            options={
                'verbose_name': 'Wöchentliche Aktivität',
                'verbose_name_plural': 'Wöchentliche Aktivitäten',
                'ordering': ['-date'],
            },
        ),
    ]
