# Generated by Django 4.2.7 on 2025-03-01 18:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreathingTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('inhale_time', models.PositiveSmallIntegerField(verbose_name='Einatmen (Sekunden)')),
                ('hold_in_time', models.PositiveSmallIntegerField(default=0, verbose_name='Halten (Sekunden)')),
                ('exhale_time', models.PositiveSmallIntegerField(verbose_name='Ausatmen (Sekunden)')),
                ('hold_out_time', models.PositiveSmallIntegerField(default=0, verbose_name='Pause (Sekunden)')),
                ('cycles', models.PositiveSmallIntegerField(default=5, verbose_name='Vorgeschlagene Zyklen')),
                ('duration', models.PositiveSmallIntegerField(verbose_name='Geschätzte Dauer (Minuten)')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Anfänger'), ('intermediate', 'Fortgeschritten'), ('advanced', 'Profi')], max_length=20, verbose_name='Schwierigkeitsgrad')),
                ('benefits', models.TextField(verbose_name='Vorteile')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Atemtechnik',
                'verbose_name_plural': 'Atemtechniken',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecommendedTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=100, verbose_name='Zustand')),
                ('priority', models.PositiveSmallIntegerField(default=1, verbose_name='Priorität')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='breathing.breathingtechnique')),
            ],
            options={
                'verbose_name': 'Empfohlene Technik',
                'verbose_name_plural': 'Empfohlene Techniken',
                'ordering': ['condition', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='BreathingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_cycles', models.PositiveSmallIntegerField(verbose_name='Abgeschlossene Zyklen')),
                ('duration_seconds', models.PositiveIntegerField(verbose_name='Dauer (Sekunden)')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Abgeschlossen am')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='breathing.breathingtechnique')),
            ],
            options={
                'verbose_name': 'Atemsitzung',
                'verbose_name_plural': 'Atemsitzungen',
                'ordering': ['-completed_at'],
            },
        ),
    ]
